services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Romminger\RrSondermetalle\:
    resource: "../Classes/*"

  Romminger\RrSondermetalle\Controller\AdminModuleController\OrderBackendModuleController:
    arguments:
      $productRepository: '@Romminger\RrSondermetalle\Domain\Repository\ProductRepository'
