base: /
languages:
  -
    title: German
    enabled: true
    languageId: 0
    base: /
    locale: de_DE.UTF-8
    navigationTitle: Deutsch
    flag: de
    hreflang: ''
    websiteTitle: ''
rootPageId: 1
websiteTitle: RR-Sondermetalle
