base: /
errorHandling:
  - errorCode: 403
    errorHandler: Page
    errorContentSource: "t3://page?uid=35"
  - errorCode: 404
    errorHandler: Page
    errorContentSource: "t3://page?uid=46"
languages:
  - title: German
    enabled: true
    languageId: 0
    base: /
    locale: de_DE.UTF-8
    navigationTitle: Deutsch
    flag: de
    hreflang: ""
    websiteTitle: ""
  - title: English
    enabled: true
    locale: en_US
    hreflang: ""
    base: /en/
    websiteTitle: ""
    navigationTitle: English
    fallbackType: strict
    fallbacks: ""
    flag: gb
    languageId: 1
rootPageId: 1
routeEnhancers:
  MaterialPlugin:
    type: Extbase
    extension: RrSondermetalle
    plugin: Material
    routes:
      - routePath: "/{material_name}"
        _controller: "Material::show"
        _arguments:
          material_name: material
    defaultController: "Material::list"
    aspects:
      material_name:
        type: PersistedAliasMapper
        tableName: tx_romminger_materials
        routeFieldName: name
  ProductPlugin:
    type: Extbase
    extension: RrSondermetalle
    plugin: Product
    routes:
      - routePath: "/{product_name}"
        _controller: "Product::show"
        _arguments:
          product_name: product
    defaultController: "product::list"
    aspects:
      product_name:
        type: PersistedAliasMapper
        tableName: tx_romminger_products
        routeFieldName: name
  CheckoutPlugin:
    type: Extbase
    extension: RrSondermetalle
    plugin: Checkout
    routes:
      - routePath: "/cart"
        _controller: "Checkout::cart"
      - routePath: "/checkout"
        _controller: "Checkout::checkout"
      - routePath: "/success"
        _controller: "Checkout::success"
      - routePath: "/invoice"
        _controller: "Checkout::invoice"
    defaultController: "checkout::cart"
websiteTitle: RR-Sondermetalle
